# Generated by Django 4.1.7 on 2023-06-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlgoTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("a", models.FloatField()),
                ("h", models.FloatField()),
                ("r", models.FloatField()),
                ("m", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="algotask",
            constraint=models.CheckConstraint(
                check=models.Q(("a__gte", 0)),
                name="a_gte_0",
                violation_error_message="Cube edge should be greater or equal than zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="algotask",
            constraint=models.CheckConstraint(
                check=models.Q(("h__gte", 0)),
                name="h_gte_0",
                violation_error_message="Cylinder height should be greater or equal than zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="algotask",
            constraint=models.CheckConstraint(
                check=models.Q(("r__gte", 0)),
                name="r_gte_0",
                violation_error_message="Cylinder radius should be greater or equal than zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="algotask",
            constraint=models.CheckConstraint(
                check=models.Q(("m__gte", 0)),
                name="m_gte_0",
                violation_error_message="Liquid volume should be greater or equal than zero",
            ),
        ),
    ]
