# Generated by Django 4.1.7 on 2023-03-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cats", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                check=models.Q(("age__lte", 120)), name="age_lte_120"
            ),
        ),
    ]
