# Generated by Django 4.1.7 on 2023-03-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cats", "0003_remove_person_age_lte_120_person_age_lte_120"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("A", "Another")], max_length=1
                    ),
                ),
                ("age", models.PositiveSmallIntegerField()),
                ("cat_name", models.CharField(max_length=30)),
                ("cat_age", models.PositiveSmallIntegerField()),
                ("breed", models.CharField(choices=[("a", "base"), ("b", "base2")], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.AddConstraint(
            model_name="visitor",
            constraint=models.CheckConstraint(
                check=models.Q(("age__lte", 120)),
                name="age_lte_120",
                violation_error_message="Age should be less or equal to 120",
            ),
        ),
        migrations.AddConstraint(
            model_name="visitor",
            constraint=models.CheckConstraint(
                check=models.Q(("cat_age__lte", 40)),
                name="cat_age_lte_40",
                violation_error_message="Cat age should be less or equal to 40",
            ),
        ),
    ]
