# Generated by Django 4.1.7 on 2023-03-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cats", "0004_visitor_delete_person_visitor_age_lte_120_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="breed",
            field=models.CharField(
                choices=[
                    ("SI", "Siamese"),
                    ("PE", "Persian"),
                    ("MC", "Maine Coon"),
                    ("RA", "Ragdoll"),
                    ("BE", "Bengal"),
                    ("AB", "Abyssinian"),
                    ("BI", "Birman"),
                    ("OS", "Oriental Shorthair"),
                    ("SX", "Sphynx"),
                    ("DR", "Devon Rex"),
                    ("HI", "Himalayan"),
                    ("AS", "American Shorthair"),
                ],
                max_length=2,
            ),
        ),
    ]
