# Generated by Django 4.1.7 on 2023-06-07 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cats", "0006_alter_visitor_cat_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="age",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(120, message="lol")]
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="cat_age",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
